version: '3.7'
name: 'nginx-microservices'
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: cont-nginx-proxy1
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./env_vars/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/certs:/data/certs
    networks:
      LAN:
        #replace ip address
        ipv4_address: XXX.XXX.XXX.XXX
        aliases:
          - cont-nginx-proxy1

volumes:
  data:

networks:
  LAN:
    external: true
